In [324]:
import numpy as np
import pandas as pd
from time import time,sleep
from random import randint as r
import random
import matplotlib.pyplot as plt
import seaborn as sns
import time
import math
from sklearn.svm import SVR
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

In [325]:
data = pd.read_csv('SMSSpamCollection.txt', delimiter="\t", header=None)
y = data[0]

In [326]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()
data_vec = vectorizer.fit_transform(data[1])

In [327]:
data_vec = pd.DataFrame(data_vec.toarray())
data_vec.columns = vectorizer.get_feature_names()

In [328]:
total_count = data_vec.shape[0]
total_spam = data.groupby([0]).count()[1][1]
total_ham = data.groupby([0]).count()[1][0]
prob_spam = total_spam/total_count
prob_ham = total_ham/total_count

In [329]:
data_vec['class'] = y
data_model = data_vec.drop('class', axis=1)

In [330]:
data_spam = data_vec[data_vec['class'] == 'spam']
data_ham = data_vec[data_vec['class'] == 'ham']
data_spam = data_spam.drop('class', axis=1)
data_ham = data_ham.drop('class', axis=1)
data_spam = data_spam.reset_index(drop=True)
data_ham = data_ham.reset_index(drop=True)
word_counts_spam = data_spam.sum()
word_counts_ham = data_ham.sum()

In [331]:
word_counts_spam = data_spam.sum()
word_counts_ham = data_ham.sum()

In [333]:
spam_word_prob = pd.DataFrame(word_counts_spam) / word_counts_spam.shape[0]
ham_word_prob = pd.DataFrame(word_counts_ham) / word_counts_ham.shape[0]

In [334]:
predictions = pd.DataFrame()
for i in range(y.shape[0]):
    
    temp = data_model.loc[[i]] # replace 0 with i
    temp = temp.replace({0:np.nan})
    temp = temp.dropna(how='all',axis='columns')
    cols = temp.columns 
    ham_class_prob = 1
    spam_class_prob = 1
    for col in cols:
        ham_class_prob = ham_class_prob*ham_word_prob.loc[col][0]
        spam_class_prob = spam_class_prob*spam_word_prob.loc[col][0]

    ham_class_prob = ham_class_prob*prob_ham
    spam_class_prob = spam_class_prob*prob_spam

    if ham_class_prob > spam_class_prob:
        predictions = predictions.append(['ham'])
    else:
        predictions = predictions.append(['spam']) 
        
    if i/1000 in ([1,2,3,4,5]): print(i)

1000
2000
3000
4000
5000


In [335]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y, predictions[0], labels=["spam", "ham"])

array([[ 743,    4],
       [   0, 4825]], dtype=int64)

In [351]:
for n, i in enumerate(pred):
    if i == 'ham':
        pred[n] = 0
    else:
        pred[n] = 1
        

In [382]:
from sklearn.metrics import roc_auc_score, f1_score, recall_score, accuracy_score, confusion_matrix, mean_squared_error, r2_score, plot_confusion_matrix

print(round(np.mean(abs(pred - np.array(y))), 2))
print(round(accuracy_score(list(np.array(y)), pred), 4))
print(round(recall_score(list(np.array(y)), pred), 4))
print(round(f1_score(list(np.array(y)), pred), 4))
print(round(roc_auc_score(list(np.array(y)), pred), 4))

0.0
0.9993
0.9946
0.9973
0.9973


In [379]:
list(np.array(y)) - pred

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [408]:
X = np.array([[-0.8945, -0.3459, 0.552],[0.4571, 0.4932, -0.4768],[-0.3825, -0.6653, 0.2855],[0.7458, 0.1253, -0.7986]])
X

array([[-0.8945, -0.3459,  0.552 ],
       [ 0.4571,  0.4932, -0.4768],
       [-0.3825, -0.6653,  0.2855],
       [ 0.7458,  0.1253, -0.7986]])

In [409]:
alpha = np.array([1.6811, 0.2384, 0.2055, 1.7139])
alpha

array([1.6811, 0.2384, 0.2055, 1.7139])

In [410]:
y = np.array([-1, -1, 1, 1])
y

array([-1, -1,  1,  1])

In [411]:
w0 = -0.0216

In [412]:
beta = np.multiply(alpha,y)
beta

array([-1.6811, -0.2384,  0.2055,  1.7139])

In [413]:
w = np.dot(beta,X)
w

array([ 2.59439418,  0.54194613, -2.12434837])

In [418]:
f = np.dot(w,X.T) + b
f 

array([-3.70238506,  2.44447471, -1.98101399,  3.67770964])

In [417]:
pred = f/abs(f)
pred

array([-1.,  1., -1.,  1.])